FROM quay.io/keycloak/keycloak:26.0.7
COPY keycloak/realm-export.json /opt/keycloak/data/import/realm-export.json
# If you have themes or certs, copy them here too
# COPY keycloak-themes /opt/keycloak/themes
# COPY certs /opt/keycloak/conf/
